# This is used by Travis CI site in order
# to produce a PDF file out of LaTeX.

addons:
  apt:
    packages:
      - texlive-full

# Decrypt private key for accessing web server
before_install:
  - openssl aes-256-cbc -K $encrypted_fa893fed2146_key
    -iv $encrypted_fa893fed2146_iv
    -in key_for_uploading.pem.enc
    -out key_for_uploading.pem -d
  - chmod 600 key_for_uploading.pem

script:
  - latexmk -pdf -pdflatex="pdflatex -interaction=nonstopmode" PothitosCV.tex

after_success:
  - scp -i key_for_uploading.pem -o StrictHostKeyChecking=no PothitosCV.pdf
    pothitos@linux02.di.uoa.gr:public_html/
  - ssh -i key_for_uploading.pem -o StrictHostKeyChecking=no
    pothitos@linux02.di.uoa.gr chmod o+r public_html/PothitosCV.pdf
